export const card = [
  {
    src: "img/catalog-decaf-flat-white.png",
    srcsetJpg: "img/catalog-decaf-flat-white@2x.png",
    srcsetWebp:"img/catalog-decaf-flat-white.webp,img/catalog-decaf-flat-white@2x.webp",
  },
  {
    src: "img/catalog-lavender.png",
    srcsetJpg:"img/catalog-lavender@2x.png",
    srcsetWebp:"img/catalog-lavender.webp,img/catalog-lavender@2x.webp",
  },
    {
    src: "img/catalog-espresso.png",
    srcsetJpg: "img/catalog-espresso@2x.png",
    srcsetWebp:"img/catalog-espresso.webp,img/catalog-espresso@2x.webp",
  },
  {
    src: "img/catalog-raspberries.png",
    srcsetJpg: "img/catalog-raspberries@2x.png",
    srcsetWebp:"img/catalog-raspberries.webp,img/catalog-raspberries@2x.webp",
  },
  {
    src: "img/catalog-mokko.png",
    srcsetJpg: "img/catalog-mokko@2x.png",
    srcsetWebp:"img/catalog-mokko.webp,img/catalog-mokko@2x.webp",
  },
  {
    src: "img/catalog-latte.png",
    srcsetJpg: "img/catalog-latte@2x.png",
    srcsetWebp:"img/catalog-latte.webp,img/catalog-latte@2x.webp",
  },
]

export const sliderCard = [
  {
    src: "img/flat-white-mobile.png",
    srcset: "img/flat-white-mobile@2x.png",
    srcsetPng768:"img/flat-white-tablet.png 1x,img/flat-white-tablet@2x.png 2x",
    srcsetPng1440:"img/flat-white-desktop.png 1x,img/flat-white-desktop@2x.png 2x",
    srcsetWebp:"img/flat-white-mobile.webp 1x,img/flat-white-mobile@2x.webp 2x",
    srcsetWebp768:"img/flat-white-tablet.webp 1x,img/flat-white-tablet@2x.webp 2x",
    srcsetWebp1440:"img/flat-white-desktop.webp 1x,img/flat-white-desktop@2x.webp 2x",
    title:"Декаф Флэт Уайт",
    description:"Свежесваренный кофе без кофеина из\u00A0Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня",
    oldPrice:"295₽",
    price:"225₽",
    color:'beige',
  },
  {
    src: "img/lavender-mobile.png",
    srcset: "img/lavender-mobile@2x.png",
    srcsetPng768:"img/lavender-tablet.png 1x,img/lavender-tablet@2x.png 2x",
    srcsetPng1440:"img/lavender-desktop.png 1x,img/lavender-desktop@2x.png 2x",
    srcsetWebp:"img/lavender-mobile.webp 1x,img/lavender-mobile@2x.webp 2x",
    srcsetWebp768:"img/lavender-tablet.webp 1x,img/lavender-tablet@2x.webp 2x",
    srcsetWebp1440:"img/lavender-desktop.webp 1x,img/lavender-desktop@2x.webp 2x",
    title:"Лавандовый Латте",
    description:"Невероятное сочетание перуанской высокогорной арабики с молоком ламы и лавандовым сиропом унесёт вас прямо на вершину Радужных гор",
    oldPrice:"285₽",
    price:"265₽",
    color:'purple',
  },
  {
    src: "img/espresso-mobile.png",
    srcset: "img/espresso-mobile@2x.png",
    srcsetPng768:"img/espresso-tablet.png 1x,img/espresso-tablet@2x.png 2x",
    srcsetPng1440:"img/espresso-desktop.png 1x,img/espresso-desktop@2x.png 2x",
    srcsetWebp:"img/espresso-mobile.webp 1x,img/espresso-mobile@2x.webp 2x",
    srcsetWebp768:"img/espresso-tablet.webp 1x,img/espresso-tablet@2x.webp 2x",
    srcsetWebp1440:"img/espresso-desktop.webp 1x,img/espresso-desktop@2x.webp 2x",
    title:"Тройной Эспрессо",
    description:"Мощнее укола адреналина, чернее самой тёмной ночи, этот тройной эспрессо из Колумбии покажет вам, что такое настоящая бодрость",
    oldPrice:"395₽",
    price:"375₽",
    color:'gray',
  },
]